### ISSUE TITLE
All functions in the example that depend on {id:[0-9]+} don't work for some reason

### ISSUE THREAD

**Issue by gustavohmsilva** [hishamhm/restserver#5]
All functions in the example that depend on {id:[0-9]+} don't work for some reason.

I'm using Lua5.3 and used the example code from the repo without any change.

The response from the server is always 404 page not found, for status, done and delete. Other operations work as expected.

Error when running using curl:

```
curl -v localhost:8080/todo/2/status
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /todo/2/status HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Length: 13
< Date: Sun, 02 Jun 2019 09:11:44 GMT
< Server: RestServer
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact

```

**Comment by otsakir** [comment]
@gustavohmsilva , in case  you're still interested, i confirmed the issue and did some digging too.

It boils down to the lua pattern syntax used when matching the paths. For some reason ranges like [0-9] don't work. Maybe it has to do with the hyphen character.

Try to use alternative patterns like [%d] where possible until this is fixed.

**Comment by otsakir** [comment]
@hishamhm , i know you're not actively involved in the project so i understand if you can't  answer. I'll ask however in case you manage.

I'm missing something with this part:

`gsub("%-", "%%-")`
    
in this line of code:

    local path = ("^/" .. name .. "/" .. entry.path):gsub("%-", "%%-"):gsub("/+", "/"):gsub("/$", "") .. "$"

https://github.com/hishamhm/restserver/blob/master/restserver.lua#L11 


The problem here lies in add_resource(). It takes paths of this form:

`useRange/{id:[0-9]+}/status`

and converts to this:

`^/todo/useRange/{id:[0%-9]+}/status$`

It puts the '%' character int the middle. Subsequent matches for incoming requests fail. So, what's the rational behind ` gsub("%-", "%%-")`. Is there a reason for treating the hyphen character as a literal ?

**Comment by hishamhm** [comment]
Hi, answering from my phone so I haven't looked at the details of the code
but thanks to your detailed description I think I can answer.

The idea is to escape hyphens that are not meant as a special character,
e.g. if entry.path is "my-resource". Lua patterns make it so that it means
"m", followed by one or more "y" matching as many as possible, followed by
"resourc", followed by... -- so what the user really wants when they type
that is "my%-resource".

Since hyphens are common in URLs I added that, but I didn't anticipate that
it would conflict with patterns inside {} captures.

I think one solution is to add some logic to split the parts of the path
between {} captures and non-capture substrings and only escape special
characters in the non-captures.

Hope this helps!

**Comment by otsakir** [comment]
Thanks @hishamhm . 

What you say makes sense.

**Comment by otsakir** [comment]
Also, checked the example .sh script. Now it works ok.
